"""
CHORUS -- Kraken Config Setup
Reads KRAKEN_API_KEY and KRAKEN_API_SECRET from .env and writes ~/.kraken/config.toml
so that kraken-cli can authenticate automatically.

Usage: python scripts/setup_kraken_config.py
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Load .env from project root
env_path = Path(__file__).resolve().parent.parent / '.env'
load_dotenv(env_path)

API_KEY = os.getenv('KRAKEN_API_KEY', '')
API_SECRET = os.getenv('KRAKEN_API_SECRET', '')

if not API_KEY or not API_SECRET:
    print('[FAIL] KRAKEN_API_KEY or KRAKEN_API_SECRET not found in .env')
    print('   Add them to your .env file first.')
    sys.exit(1)

# Create ~/.kraken directory
kraken_dir = Path.home() / '.kraken'
kraken_dir.mkdir(exist_ok=True)

config_path = kraken_dir / 'config.toml'

# Write config.toml
config_content = f"""# Kraken CLI configuration -- auto-generated by CHORUS
# DO NOT commit this file. It contains your API credentials.

[auth]
api_key = "{API_KEY}"
api_secret = "{API_SECRET}"
"""

config_path.write_text(config_content)
print(f'[OK] Kraken CLI config written to: {config_path}')
print(f'   API Key: {API_KEY[:8]}...{API_KEY[-4:]}')
print(f'   API Secret: {API_SECRET[:8]}...{API_SECRET[-4:]}')
print('')
print('Test your connection with:')
print('   kraken-cli account balance')
